name: Deploy Website

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'website@')
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        working-directory: ./apps/website
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBSITE_PROJECT_ID }}
        run: |
          npx vercel deploy --prod --token=$VERCEL_TOKEN --yes
